
Component({
    properties:{
        brand:{
            type:String,
            value:''
        }
    },
    data:{
        wH:0,
        arr:['宝马','奥迪','丰田','本田','大众'],
        nowshow:'main',
        nowchoose:''
    },
    lifetimes:{
        attached(){
            wx.getSystemInfo({
              success: (res) => {
                this.setData({
                    wH:res.windowHeight
                })
              },
            });
            this.setData({
                nowchoose:this.properties.brand
            })
        }
    },
    methods:{
        showallbrand(){
            this.setData({
                nowshow:'allbrand'
            })
        },
        okH(){
            this.triggerEvent('ok',{'brand':this.data.nowchoose})
        },
        pinpaiH(e){
            this.setData({
                nowchoose:e.target.dataset.brand
            })
        },
        ok(e){
            this.setData({
                nowchoose:e.detail.nowcur,
                nowshow:'main'
            })
        },
        quxiao(){
            this.triggerEvent('close')
        },
        reset(){
            this.setData({
                nowchoose:''
            })
        },
        close(){
            this.setData({
                nowshow:'main'
            })
        }
    }
})